export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATED_ADMIN = 'AUTHENTICATION_ADMIN';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';