export const COMMUNITY_CREATED = 'COMMUNITY_CREATED';
export const COMMUNITY_CREATING = 'COMMUNITY_CREATING';
export const COMMUNITY_CREATION_ERROR = 'COMMUNITY_CREATION_ERROR';
export const COMMUNITY_UPDATED = 'COMMUNITY_UPDATED';
export const COMMUNITY_UPDATING = 'COMMUNITY_UPDATING';
export const COMMUNITY_UPDATING_ERROR = 'COMMUNITY_UPDATING_ERROR';