/*<a href="#">HOME</a>
  <a href="#">HOME</a>
<a href="#">FEED</a>
              <a href="#">PROFILE</a>
              <a href="#">LOGIN</a>
              <a href="#">REGISTER</a>
              <a href="#">ABOUT US</a>
              <a href="#">TERMS AND AGREEMENTS</a>
              <a href="#">PRIVACY & POLICY</a>
              <a href="#">BACKOFFICE</a>
              <a href="#">LOGOUT</a>*/